services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: password
      DB_DATABASE: exampledb
      DB_PORT: 5432
      NODE_ENV: production
    secrets:
      - admin_password
      - gemini_key

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: exampledb
      TZ: "America/Chicago"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

secrets:
  admin_password:
    file: /home/leo/admin_password.txt
  gemini_key:
    file: /home/leo/gemini_key.txt

volumes:
  postgres_data:
